version: '3.8'

services:
  app:
    container_name: app
    image: app
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - ./app/:/code
    ports:
      - 8080:8080
    env_file:
      - ${ENV_FILE}
