version: '3.8'

services:
  app:
    container_name: app
    image: app
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level error
    volumes:
      - ./app/:/code
    ports:
      - 8080:8000
    env_file:
      - ${ENV_FILE}
    networks:
      - yar_network

  mongodb:
    container_name: mongodb
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - yar_network

volumes:
  mongodb_data:

networks:
  yar_network:
    driver: bridge