name: Testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  testing:
    name: Testing...
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - name: Copy code and git pull
      uses: actions/checkout@v3
    - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
    - name: Create env-file
      run: echo "${{ secrets.ENV_FILE }}" > example.env
    - name: Run docker-compose
      run: ENV_FILE=./example.env docker-compose up -d
    - name: Run tests
      run: ENV_FILE=./example.env docker-compose exec -T web python -m pytest
    - run: echo "This job's status is ${{ job.status }}."